### ISSUE TITLE
Merge work from ICCS MiMA repo into the datawave repo

### ISSUE THREAD

**Issue by jatkinson1000** [DataWaveProject/MiMA-machine-learning#6]
ICCS have a fork of MiMA where they have been doing some DataWave work.
This should really be in the DataWave fork of MiMA so that ownership on any code remains with DataWave.
It also means all PRs and issues can be held in one place to avoid confusion.

We need to:
- [x] Transfer any work and branches from ICCS to DataWave
- [x] Transfer any issues from ICCS to DataWave
- [x] Transfer outstanding CMake PR from ICCS to MJucker main repo to here
- [x] Update datawave/ICCS folks so they know what we've done
- [x] Archive the ICCS forked repo and point people to this repo.

**Comment by jatkinson1000** [comment]
I am about to tackle this.
TODO:
- [x] Clone DataWave fork
- [x] Add ICCS fork locally as a second remote
- [x] Pull open branches from ICCS to DataWave
  - [x] cmake
  - [x] forpy
  - [x] forpy_CMake
- [x] Push back up to DataWave

**Comment by jatkinson1000** [comment]
I couldn't find a clean way of transferring a PR between repos, so I closed [PR #33](https://github.com/mjucker/MiMA/pull/33) from ICCS fork and opened [PR #34](https://github.com/mjucker/MiMA/pull/34) from the cmake branck on this repo. The code is exactly the same and I copied across any comments from #33.

**Comment by jatkinson1000** [comment]
@dorchard I do not have admin priveledges on [ICCS MiMA fork](https://github.com/Cambridge-ICCS/MiMA/tree/cmake) Please could you add me so I can archive the repo (or can you archive it (and redirect here if possible))? Thanks.

**Comment by jatkinson1000** [comment]
@SimonClifford I think the transfer from [ICCS MiMA](https://github.com/Cambridge-ICCS/MiMA/tree/cmake) to this repo is now complete ~(apart from archiving the ICCS repo)~. Since there isn't a PR as such could you perhaps cast a second pair of eyes over and check everything looks OK? I'll then close this issue.

**Comment by dorchard** [comment]
Archived ICCS one.

**Comment by mondus** [comment]
@jatkinson1000 Am I missing something? I don't see any PRs on this DataWave fork of MiMA. I think you might have accidently opened it again on our [local ICCS copy](https://github.com/mjucker/MiMA/pull/34).

**Comment by jatkinson1000** [comment]
@mondus That is the correct PR, but according to my view it is coming from [the `cmake` branch of the DataWaveProject fork of MiMA](https://github.com/DataWaveProject/MiMA/tree/cmake)?
![image](https://user-images.githubusercontent.com/109271713/225873455-977cc2f7-08c0-4c26-8296-a2b188a832d9.png)

**Comment by jatkinson1000** [comment]
@mondus I think I understand the confusion now...

To clarify - MiMA is a code developed by Martin Jucker, previously NYU and now in Australia, and has been used by DataWave as a testbed for their ML parameterisations.
As part of the DataWave work we implemented a CMake build process that we feel is easier to use than the current mkmf build process, so decided to contribute it back to the original project.
So the PR has been opened from this repository into [Martin's master repository of MiMA](https://github.com/mjucker/MiMA) which is what you linked above.

I guess this partly illustrates the need for not having multiple forks and a well-defined working procedure.

**Comment by jatkinson1000** [comment]
@mondus are you happy for me to close this?
